CREATE TABLE `dwd_device_all_rt` (
                                     `device_id` VARCHAR(200) NULL COMMENT '设备id',
                                     `acquire_timestamp_format` DATETIME NULL COMMENT '采集时间戳格式化',
                                     `acquire_timestamp` BIGINT NULL COMMENT '采集时间戳',
                                     `product_key` VARCHAR(200) NULL COMMENT '产品编码',
                                     `type` VARCHAR(200) NULL COMMENT '类型',
                                     `tid` VARCHAR(200) NULL COMMENT '当前请求的事务唯一ID',
                                     `bid` VARCHAR(200) NULL COMMENT '长连接整个业务的ID',
                                     `method` VARCHAR(200) NULL COMMENT '服务&事件标识',
                                     `version` VARCHAR(200) NULL COMMENT '版本',
                                     `aircraft_model` VARCHAR(200) NULL COMMENT '飞机型号',
                                     `has_eO` VARCHAR(200) NULL COMMENT '是否携带EO传感器',
                                     `aircraft_number` INT NULL COMMENT '飞机编号',
                                     `route_number` INT NULL COMMENT '当前航线号',
                                     `target_route_number` INT NULL COMMENT '目标航线号',
                                     `target_way_point_number` INT NULL COMMENT '目标航点号',
                                     `longitude` DOUBLE NULL COMMENT '经度',
                                     `latitude` DOUBLE NULL COMMENT '纬度',
                                     `yaw` DOUBLE NULL COMMENT '方位角',
                                     `pitch` DOUBLE NULL COMMENT '俯仰角',
                                     `altitude` DOUBLE NULL COMMENT '海拔高度',
                                     `eastbound_velocity` DOUBLE NULL COMMENT '东向速度',
                                     `northbound_velocity` DOUBLE NULL COMMENT '北向速度',
                                     `celestial_velocity` DOUBLE NULL COMMENT '天向速度',
                                     `current_link_usage` VARCHAR(200) NULL COMMENT '当前使用链路',
                                     `recorder_download_status` VARCHAR(200) NULL COMMENT '记录器传输状态',
                                     `recorder_download_type` VARCHAR(200) NULL COMMENT '下传信息类型',
                                     `record_status` VARCHAR(200) NULL COMMENT '记录状态',
                                     `record_download_bandwidth` VARCHAR(200) NULL COMMENT '实时传输带宽选择',
                                     `record_download_compression_ratio` VARCHAR(200) NULL COMMENT '控制传输压缩比',
                                     `ccd_status` VARCHAR(200) NULL COMMENT 'CCD工作状态',
                                     `ccd_take_photo_mode` VARCHAR(200) NULL COMMENT 'CCD拍照模式',
                                     `eo_mode` VARCHAR(200) NULL COMMENT 'EO-传感器选择回报',
                                     `eo_yaw` DOUBLE NULL COMMENT 'EO-方位角',
                                     `eo_pitch` DOUBLE NULL COMMENT 'EO-俯仰角',
                                     `eo_fov` INT NULL COMMENT 'EO-激光测距值',
                                     `eo_laser_distance` INT NULL COMMENT 'EO-传感器视场',
                                     `eo_tracking_method` VARCHAR(200) NULL COMMENT 'EO-跟踪方式回报',
                                     `eo_laser_status` VARCHAR(200) NULL COMMENT 'EO-激光器状态',
                                     `eo_infrared_power_status` VARCHAR(200) NULL COMMENT 'EO-红外上电状态',
                                     `eo_laser_power_status` VARCHAR(200) NULL COMMENT 'EO-激光上电状态',
                                     `target_longitude` DOUBLE NULL COMMENT '目标经度',
                                     `target_latitude` DOUBLE NULL COMMENT '目标纬度',
                                     `target_altitude` INT NULL COMMENT '目标海拔高度',
                                     `target_range` INT NULL COMMENT '目标距离',
                                     `target_yaw` DOUBLE NULL COMMENT '目标方位',
                                     `target_pitch` DOUBLE NULL COMMENT '目标俯仰',
                                     `sar_status` VARCHAR(200) NULL COMMENT '雷达工作状态(SAR)',
                                     `sar_mode` VARCHAR(200) NULL COMMENT 'SAR工作模式',
                                     `sar_resolution` VARCHAR(200) NULL COMMENT 'SAR分辨率',
                                     `sar_system_mode` VARCHAR(200) NULL COMMENT 'SAR系统模式',
                                     `sar_effect_distance` INT NULL COMMENT 'SAR作用距离',
                                     `update_time` DATETIME NULL COMMENT '数据入库时间'
) ENGINE=OLAP
UNIQUE KEY(`device_id`, `acquire_timestamp_format`)
COMMENT '设备轨迹数据全部入库'
PARTITION BY RANGE(`acquire_timestamp_format`)()
DISTRIBUTED BY HASH(`device_id`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Etc/UTC",
"dynamic_partition.start" = "-90",
"dynamic_partition.end" = "1",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "20",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "10",
"dynamic_partition.hot_partition_num" = "0",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.storage_policy" = "",
"dynamic_partition.storage_medium" = "HDD",
"storage_format" = "V2",
"inverted_index_storage_format" = "DEFAULT",
"enable_unique_key_merge_on_write" = "false",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728"
);